export const SET_ORDERNUM = "SET_ORDERNUM";

export const SET_ORDERS = "SET_ORDERS";

export const SET_ORDERS_PAGE = "SET_ORDERS_PAGE";

export const DEL_ORDERS = "DEL_ORDERS";

export const SET_STATUS = "SET_STATUS";

export const SET_ORDER_INFO = "SET_ORDER_INFO";

export const SET_REVIEW_ORDERS = "SET_REVIEW_ORDERS";

export const SET_REVIEW_ORDERS_PAGE = "SET_REVIEW_ORDERS_PAGE";

export const SET_REVIEW_SERVICES = "SET_REVIEW_SERVICES";

export const SET_REVIEW_SCORE = "SET_REVIEW_SCORE";
